### PR TITLE
Finnish

### PR DESCRIPTION
**Pull request by supertassu**
Hello!
I am added finnish langue.

### CODE REVIEW

**Comment by Luca0208** [comment]
Thank you, how do you say "finnish" in finnish(For language selection)

**Comment by Ale32bit** [comment]
The language isn't compatible

**Comment by supertassu** [comment]
@Luca0208 It is "suomi"

**Comment by Luca0208** [comment]
Ale is right, The language isn't compatible. In german we can replace "ä" with "ae", is there that sort of thing for your language, because characters like äöü will result into bugs if printed!

**Comment by supertassu** [comment]
I can fix.

**Comment by supertassu** [comment]
@Luca0208 @Ale32bit  I fixed it.

**Comment by Luca0208** [comment]
K, i will implement it

**Comment by Luca0208** [comment]
Thanks for the translation

**Pull request merged**
